services:
  db:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - back-tier

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY_PATH=/run/secrets/secret_key
      - DATABASE_HOST=db
    ports:
      - "8000:5000"
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier
    secrets:
      - secret_key

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

secrets:
  secret_key:
    file: ./instance/secret_key.json