services:
  db:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - back-tier

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY_PATH=/run/secrets/secret_key
      - DATABASE_HOST=db
      - NGINX_CONF=./nginx/nginx.conf
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - front-tier
      - back-tier
    secrets:
      - secret_key

  nginx-proxy:
      image: nginx:latest
      ports:
        - "8080:80"
        - "8081:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - front-tier
      depends_on:
        - app
    
volumes:
  db-data:

networks:
  front-tier:
  back-tier:

secrets:
  secret_key:
    file: ./instance/secret_key.json